#!/bin/bash
echo "🚨 Installing Yabai Scripting Addition"
echo "This enables full Yabai functionality including space switching"
echo ""
echo "⚠️  WARNING: This requires partially disabling System Integrity Protection (SIP)"
echo "This reduces system security but enables advanced window management"
echo ""
echo "Steps to install scripting addition:"
echo ""
echo "1. Reboot into Recovery Mode:"
echo "   • Restart Mac and hold Command ⌘ + R"
echo "   • Wait for Recovery Mode to load"
echo ""
echo "2. In Recovery Mode, open Terminal and run:"
echo "   csrutil disable"
echo ""  
echo "3. Reboot into normal macOS"
echo ""
echo "4. Install the scripting addition:"
echo "   sudo /opt/homebrew/bin/yabai --install-sa"
echo "   sudo /opt/homebrew/bin/yabai --load-sa"
echo ""
echo "5. Reboot into Recovery Mode again and run:"
echo "   csrutil enable --without fs --without debug --without nvram"
echo ""
echo "6. Reboot into normal macOS"
echo ""
echo "7. Restart Yabai:"
echo "   /opt/homebrew/bin/yabai --restart-service"
echo ""
echo "💡 After this, all hotkeys including space switching will work!"
